[package]
name = "turnhammer"
description = "A tool to stress-test TURN (RFC 5766) servers"
version = "0.1.0"
authors = ["Vitaly _Vi Shukela <vi0oss@gmail.com>"]
edition = "2018"
keywords = [ "rfc5766", "turn", "networking"]

[dependencies]
rusturn = "0.0.3"
rustun = "0.3.5"
futures = "0.1.25"
tokio = "0.1.15"
structopt = "0.2.14"
